import React, { useState, useRef, useEffect } from 'react';
import DynamicRenderer, { type DynamicRendererHandle } from './DynamicRenderer';

interface Message {
    id: string;
    role: 'user' | 'ai';
    content: string;
    isComponent?: boolean;
    componentCode?: string;
    model?: 'gemini' | 'anthropic';
}

const ChatInterface: React.FC = () => {
    const [messages, setMessages] = useState<Message[]>([]);
    const [input, setInput] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [activeComponentCode, setActiveComponentCode] = useState<string | null>(null);
    const [isChatExpanded, setIsChatExpanded] = useState(true);
    const [selectedModel, setSelectedModel] = useState<'gemini' | 'anthropic'>('gemini');
    const rendererRef = useRef<DynamicRendererHandle>(null);
    const chatContainerRef = useRef<HTMLDivElement>(null);

    const abortControllerRef = useRef<AbortController | null>(null);

    useEffect(() => {
        if (chatContainerRef.current) {
            chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
        }
    }, [messages, isLoading]);

    const handleCancel = () => {
        if (abortControllerRef.current) {
            abortControllerRef.current.abort();
            abortControllerRef.current = null;
            setIsLoading(false);
            setMessages(prev => [...prev, {
                id: Date.now().toString(),
                role: 'ai',
                content: 'Request canceled by user.',
                model: selectedModel
            }]);
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!input.trim()) return;

        const userMessage: Message = {
            id: Date.now().toString(),
            role: 'user',
            content: input,
        };

        setMessages(prev => [...prev, userMessage]);
        setInput('');
        setIsLoading(true);
        setIsChatExpanded(true);

        // Create new AbortController
        const controller = new AbortController();
        abortControllerRef.current = controller;

        // Set timeout
        const timeoutId = setTimeout(() => {
            controller.abort();
        }, 45000); // 45 seconds timeout

        try {
            const response = await fetch('http://localhost:3000/api/generate-jsx', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ prompt: input, model: selectedModel }),
                signal: controller.signal
            });

            clearTimeout(timeoutId);

            if (!response.ok) {
                throw new Error(`Server error: ${response.status}`);
            }

            const data = await response.json();

            if (data.code) {
                const aiMessage: Message = {
                    id: (Date.now() + 1).toString(),
                    role: 'ai',
                    content: selectedModel === 'gemini' ? "Generated by Gemini" : "Generated by Claude",
                    componentCode: data.code,
                    model: selectedModel
                };
                setMessages(prev => [...prev, aiMessage]);
                setActiveComponentCode(data.code);
                setIsChatExpanded(false);
            } else {
                throw new Error('No code returned from server');
            }
        } catch (error) {
            if (error instanceof Error) {
                if (error.name === 'AbortError') {
                    setMessages(prev => [...prev, {
                        id: Date.now().toString(),
                        role: 'ai',
                        content: 'Request timed out after 45 seconds.',
                        model: selectedModel
                    }]);
                } else {
                    console.error('Error:', error);
                    setMessages(prev => [...prev, {
                        id: Date.now().toString(),
                        role: 'ai',
                        content: `Error: ${error.message}. Please try again.`,
                        model: selectedModel
                    }]);
                }
            }
        } finally {
            setIsLoading(false);
            abortControllerRef.current = null;
            clearTimeout(timeoutId);
        }
    };

    return (
        <div className="relative h-screen w-screen overflow-hidden bg-slate-950 font-sans selection:bg-blue-500/30">
            {/* Canvas Layer (Background) */}
            <div className="absolute inset-0 z-0">
                {/* Dynamic Background */}
                <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900 via-slate-950 to-black opacity-80" />

                {/* Grid Pattern */}
                <div
                    className="absolute inset-0 opacity-[0.05] pointer-events-none"
                    style={{
                        backgroundImage: 'linear-gradient(to right, #4f4f4f2e 1px, transparent 1px), linear-gradient(to bottom, #4f4f4f2e 1px, transparent 1px)',
                        backgroundSize: '4rem 4rem',
                        maskImage: 'radial-gradient(ellipse 60% 50% at 50% 0%, #000 70%, transparent 100%)'
                    }}
                />

                {/* Ambient Glow */}
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] bg-blue-500/10 blur-[120px] rounded-full pointer-events-none" />

                {activeComponentCode ? (
                    <div className={`w-full h-full transition-all duration-700 ease-out ${isChatExpanded ? 'opacity-20 scale-[0.95] blur-sm translate-y-4' : 'opacity-100 scale-100 blur-0 translate-y-0'}`}>
                        <DynamicRenderer ref={rendererRef} code={activeComponentCode} />
                    </div>
                ) : (
                    <div className="flex items-center justify-center h-full text-slate-400">
                        <div className="text-center space-y-6 max-w-lg px-6">
                            <div className="relative inline-block">
                                <div className="absolute inset-0 bg-blue-500/20 blur-xl rounded-full animate-pulse" />
                                <div className="relative bg-slate-900/50 backdrop-blur-xl border border-slate-800 p-4 rounded-2xl shadow-2xl ring-1 ring-white/10">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="text-blue-400">
                                        <path d="M12 2a10 10 0 1 0 10 10 4 4 0 0 1-5-5 4 4 0 0 1-5-5" />
                                        <path d="M8.5 8.5v.01" />
                                        <path d="M16 15.5v.01" />
                                        <path d="M12 12v.01" />
                                    </svg>
                                </div>
                            </div>
                            <div>
                                <h2 className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-b from-white to-slate-400 mb-3 tracking-tight">
                                    {selectedModel === 'gemini' ? 'Gemini' : 'Claude'} Assistant
                                </h2>
                                <p className="text-lg text-slate-500 leading-relaxed">
                                    Ask a question or describe a UI to generate <span className="text-blue-400 font-medium">interactive components</span> instantly.
                                </p>
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* UI Layer (Foreground) */}
            <div className="absolute inset-0 z-10 pointer-events-none flex flex-col justify-end items-center pb-6 sm:pb-10">
                {/* Chat History (Floating & Collapsible) */}
                <div
                    className={`w-full max-w-3xl px-4 pointer-events-auto flex flex-col gap-6 transition-all duration-500 ease-[cubic-bezier(0.23,1,0.32,1)] ${isChatExpanded ? 'max-h-[60vh] opacity-100 mb-8' : 'max-h-0 opacity-0 mb-0 overflow-hidden'
                        }`}
                >
                    <div
                        ref={chatContainerRef}
                        className="overflow-y-auto flex flex-col gap-6 mask-image-gradient-vertical pb-4 px-2 scrollbar-hide"
                    >
                        {messages.map(msg => (
                            <div
                                key={msg.id}
                                className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} animate-in fade-in slide-in-from-bottom-4 duration-500`}
                            >
                                <div
                                    className={`max-w-[85%] sm:max-w-[75%] rounded-3xl px-6 py-4 shadow-xl backdrop-blur-md transition-all duration-300 ${msg.role === 'user'
                                        ? 'bg-gradient-to-br from-blue-600 to-violet-600 text-white shadow-blue-900/20'
                                        : 'bg-slate-900/80 text-slate-200 border border-slate-800 shadow-black/20'
                                        } ${msg.componentCode ? 'cursor-pointer hover:scale-[1.02] hover:shadow-2xl hover:border-blue-500/30 group ring-1 ring-transparent hover:ring-blue-500/20' : ''}`}
                                    onClick={() => {
                                        if (msg.componentCode) {
                                            setActiveComponentCode(msg.componentCode);
                                            setIsChatExpanded(false);
                                        }
                                    }}
                                >
                                    <div className="text-[15px] leading-relaxed flex flex-col gap-2">
                                        {msg.content}
                                        {msg.componentCode && (
                                            <button
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    setActiveComponentCode(msg.componentCode!);
                                                    setIsChatExpanded(false);
                                                }}
                                                disabled={activeComponentCode === msg.componentCode || isLoading}
                                                className={`flex items-center gap-2 text-xs font-medium uppercase tracking-wider mt-2 transition-all duration-300 px-3 py-1.5 rounded-lg border ${activeComponentCode === msg.componentCode
                                                    ? 'bg-green-500/10 text-green-400 border-green-500/20 cursor-default'
                                                    : isLoading
                                                        ? 'bg-slate-800/50 text-slate-500 border-slate-700 cursor-not-allowed opacity-50'
                                                        : 'bg-blue-500/10 text-blue-400 border-blue-500/20 hover:bg-blue-500/20 hover:text-blue-300 cursor-pointer'
                                                    }`}
                                            >
                                                {activeComponentCode === msg.componentCode ? (
                                                    <>
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                                            <path d="M2 12h10" />
                                                            <path d="M9 5l3 7-3 7" />
                                                            <path d="M13.5 7.5L22 12l-8.5 4.5" />
                                                        </svg>
                                                        Viewing
                                                    </>
                                                ) : (
                                                    <>
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                                            <path d="M15 3h6v6" />
                                                            <path d="M10 14L21 3" />
                                                            <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                                                        </svg>
                                                        View Response
                                                    </>
                                                )}
                                            </button>
                                        )}
                                    </div>
                                </div>
                            </div>
                        ))}
                        {isLoading && (
                            <div className="flex justify-start animate-in fade-in slide-in-from-bottom-2 duration-500">
                                <div className="bg-slate-900/80 backdrop-blur-md rounded-3xl px-6 py-4 shadow-xl border border-slate-800 flex items-center gap-4">
                                    <div className="flex gap-1.5">
                                        <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                                        <div className="w-2 h-2 bg-violet-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                                        <div className="w-2 h-2 bg-indigo-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                                    </div>
                                    <button
                                        onClick={handleCancel}
                                        className="text-xs font-medium text-red-400 hover:text-red-300 hover:bg-red-500/10 px-2 py-1 rounded transition-colors"
                                    >
                                        Cancel
                                    </button>
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Input Bar (Floating) */}
                <div className="w-full max-w-3xl px-4 pointer-events-auto relative group">
                    {/* Toggle Chat Button */}
                    <button
                        onClick={() => setIsChatExpanded(!isChatExpanded)}
                        className="absolute -top-16 right-4 bg-slate-900/80 backdrop-blur-xl p-3 rounded-full shadow-lg border border-slate-800 hover:bg-slate-800 hover:border-slate-700 transition-all duration-300 text-slate-400 hover:text-white hover:scale-110 active:scale-95"
                        title={isChatExpanded ? "Collapse Chat" : "Expand Chat"}
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={`transition-transform duration-500 ${isChatExpanded ? 'rotate-180' : ''}`}>
                            <polyline points="18 15 12 9 6 15"></polyline>
                        </svg>
                    </button>

                    {/* Scroll to Bottom Button */}
                    {!isChatExpanded && activeComponentCode && (
                        <button
                            onClick={() => rendererRef.current?.scrollToBottom()}
                            className="absolute -top-16 right-16 bg-slate-900/80 backdrop-blur-xl p-3 rounded-full shadow-lg border border-slate-800 hover:bg-slate-800 hover:border-slate-700 transition-all duration-300 text-slate-400 hover:text-white hover:scale-110 active:scale-95"
                            title="Scroll to Bottom"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                <path d="M12 5v14M19 12l-7 7-7-7" />
                            </svg>
                        </button>
                    )}

                    <form
                        onSubmit={handleSubmit}
                        className="relative bg-slate-900/60 backdrop-blur-2xl border border-slate-800/60 shadow-2xl rounded-[2rem] p-2 flex gap-2 ring-1 ring-white/5 transition-all duration-300 focus-within:ring-blue-500/50 focus-within:bg-slate-900/80 focus-within:border-slate-700 focus-within:shadow-blue-900/20 hover:border-slate-700"
                    >
                        <div className="flex items-center pl-4">
                            <select
                                value={selectedModel}
                                onChange={(e) => setSelectedModel(e.target.value as 'gemini' | 'anthropic')}
                                className="bg-slate-800/50 text-slate-300 text-sm rounded-lg border border-slate-700 focus:ring-blue-500 focus:border-blue-500 block p-2.5 outline-none cursor-pointer hover:bg-slate-800 transition-colors"
                            >
                                <option value="gemini">Gemini</option>
                                <option value="anthropic">Claude</option>
                            </select>
                        </div>
                        <input
                            type="text"
                            value={input}
                            onChange={e => setInput(e.target.value)}
                            placeholder={`Ask ${selectedModel === 'gemini' ? 'Gemini' : 'Claude'} a question...`}
                            className="flex-1 bg-transparent border-none px-4 py-4 focus:outline-none text-slate-100 placeholder-slate-500 text-lg font-light"
                        />
                        <button
                            type="submit"
                            disabled={isLoading}
                            className="bg-gradient-to-r from-blue-600 to-violet-600 text-white px-8 py-4 rounded-[1.5rem] hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed font-medium transition-all duration-300 shadow-lg shadow-blue-900/30 hover:shadow-blue-600/40 hover:scale-[1.02] active:scale-[0.98]"
                        >
                            <span className="flex items-center gap-2">
                                Send
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <line x1="22" y1="2" x2="11" y2="13"></line>
                                    <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
                                </svg>
                            </span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default ChatInterface;
